### ISSUE TITLE
[Task] (사용자정보) 개인 정보 수정

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/Memory-It#11]
## ISSUE
+ Group: `server`
+ Type: `feature`
+ Detail: 개인정보 수정을 이용해 개인정보 수정요청시 유저의 정보를 변경

## TODO
- [x] 토큰을 이용해 인증된 유저인지 확인
- [x] 유저가 입력한 변경 사항이 유효한지에 따른 처리
- [x] 변경사항이 유효하다면 변경 성공을 응답
- [x] 변경사항이 유효하지 않다면 오류코드를 응답

## Estimated time
> 하나만 선택해 주세요.

- [x] 6h

## Labels
Estimated time: `E: 6h`
Group : `server`
Urgency: `Middle`
