### ISSUE TITLE
[Task] MyPost 내 컴포넌트 작성

### ISSUE THREAD

**Issue by rkems0122** [codestates/Memory-It#15]
## ISSUE

+ Group: `client`
+ Type:  `feature`
+ Detail: MyPost 내 Sidebar, Header, Body, Post(Body 내에 존재) 컴포넌트를 작성합니다.
## TODO
- [ ] Sidebar 컴포넌트 작성
- [ ] Header 컴포넌트 작성
- [ ] Body 컴포넌트 작성
- [ ] Post 컴포넌트 작성
## Estimated time

- [ ] 6h
## Labels
Estimated time: `E: 6h`
Group : `client`
Sprint: `Sprint__2__`
Urgency: `High`
