### ISSUE TITLE
[Task] PostDetail 페이지 안의 컴포넌트 작성

### ISSUE THREAD

**Issue by rkems0122** [codestates/Memory-It#17]
## ISSUE

+ Group: `client`
+ Type:  `feature`
+ Detail: PostDetail 안에 존재하는 Picture, Map, Content 컴포넌트를 작성합니다.
## TODO
- [ ] Picture 컴포넌트 작성
- [ ] Map 컴포넌트 작성
- [ ] Content 컴포넌트 작성

## Estimated time

- [ ] 6h
## Labels
Estimated time: `E: 6h`
Group : `client`
Sprint: `Sprint__2__`
Urgency: `High`
