### ISSUE TITLE
[Task] (사용자정보) 로그인

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/Memory-It#19]
## ISSUE

+ Group: `server`
+ Type: `feature`
+ Detail: 로그인요청 처리

## TODO
- [x] 유저의 입력이 유효한지에 따른 처리
- [x] 유저의 입력이 유효하다면 입력받은 이메일이 DB에 있는 유저인지에 따른 처리
- [ ] 있다면 입력받은 비밀번호를 서버에서 사용중인 해싱함수로 해싱 후 해당 유저의 DB비밀번호와 매칭
- [x] 일치한다면 토큰, 유저정보 응답
- [x] 불일치한다면 오류코드 응답

## Estimated time
> 하나만 선택해 주세요.

- [ ] 3h

## Labels
Estimated time: `E: 3h`
Group : `server`
Urgency: `Middle`
