### ISSUE TITLE
[TODO LIST] 🔥🔥 todos 🔥🔥

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/Memory-It#2]
구현에 따라 체크박스를 하나씩 체크해가면서, 프로젝트의 필수 혹은 권장할 만한 진행 상황을 확인할 수 있습니다.

## 1. 시스템 아키텍처
- [x] JWT를 이용한 로그인 구현 | 필수 | ★
- [x] OAuth 2.0을 이용한 소셜 로그인 | 권장 | ★

## 2. UI/UX
- [x] 회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 기능 구현 | 필수 | 프론트엔드, 백엔드 | ★
- [x] 회원가입, 로그인 및 회원정보 수정 시 유효성 검사 | 필수 | 프론트엔드 | ★ 
- [x] 소셜 로그인 외 서비스 자체 회원가입 기능 제공 | 필수 | 프론트엔드 | ★ 
- [ ] 회원 탈퇴나 리소스 삭제시 확인(confirm) 모달 제공 | 권장 | 프론트엔드 | ★ 
- [x] 마이페이지를 통해 사용자 개인정보 수정 기능 제공 | 필수 | 프론트엔드 | ★ 
- [x] (소셜 로그인이 아닐 경우) 비밀번호 수정 기능 제공 | 필수 | 프론트엔드 | ★
- [x] 라이브러리를 사용하지 않고 React 컴포넌트 직접 작성 (유어클래스에서 다룬 것) | 필수 | ★
- [x] 3rd-party API 호출(kakao map API)| 권장 | ★
- [ ] 게시물 작성 시 이미지와 각 이미지의 좌표정보, 배경색상을 포함시켜 서버에 제공 | ★★★★
- [x] 게시물 삭제 기능 제공 | ★
- [x] 달력기능 구현 | ★★
- [x] 게시물 상세보기 기능 제공 | ★★
- [x] 작성한 게시물들을 지도에 마커로 표시 | ★★

## 3. 스키마 및 API
- [x] N:M (다대다) 관계 설정 | 필수 | ★
- [x] ERD (DB Diagram) 작성 | 필수 | ★
- [x] API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★

### DB
- [x] ORM 사용 (TypeORM) | 권장 | ★
- [x] TypeScript 언어 사용 | ★★★

## 4. DevOps
- [x] [코드] precommit 단계에서 semistandard 적용 | 필수 | ★
- [x] [릴리즈] 깃허브 커밋메세지 규칙 합의 | 필수 | ★
- [x] [코드] 버전 규칙 합의 | 필수 | ★
- [x] [릴리즈] PR 형식 합의 | 권장 | ★
- [x] [배포] 도메인 구매 및 HTTPS 배포 | 권장 | ★★★
- [x] [배포] S3로 파일 업로드 | 권장 | ★★★
- [x] [배포] EC2로 클라우드 컴퓨팅 | 권장 | ★★★
- [x] [배포] RDS로 DB관리

## Advanced (도전) 항목을 추가적으로 구현할 계획이라면, 아래에 적어주세요
**UX/UI**
- [x] 모바일 환경 대응 및 반응형 웹 | 권장 | ★★
- [ ] 무한 스크롤(or 페이지네이션) | ★★★
- [ ] 스크롤에 의한 애니메이션 적용 (greensock 사용 권장) | ★★★

**인증/배포**
- [ ] 회원 가입시 인증 메일 발송 | 권장 | ★★★
- [ ] [배포] 배포 자동화 설정 | 권장 | ★
- [ ] [테스트] w3c validator 통과 | 권장 | ★★★

## Nightmare (신중) 항목을 추가적으로 구현할 계획이라면, 아래에 적어주세요
- [ ] 컬러맵 sns공유 ★★★★
