### ISSUE TITLE
[Task] ColorMap 페이지 안의 컴포넌트 작성

### ISSUE THREAD

**Issue by rkems0122** [codestates/Memory-It#20]
## ISSUE

+ Group: `client`
+ Type:  `feature`
+ Detail: ColorMap 페이지 안의 ColorMap, Share, ChangeView 컴포넌트를 작성합니다.
## TODO
- [ ] ColorMap 컴포넌트 작성
- [ ] Share 컴포넌트 작성
- [ ] ChangeView 컴포넌트 작성

## Estimated time

- [ ] 6h
## Labels
Estimated time: `E: 6h`
Group : `client`
Sprint: `Sprint__2__`
Urgency: `High`
