### ISSUE TITLE
[Task] Login 전 페이지의 컴포넌트 작성

### ISSUE THREAD

**Issue by rkems0122** [codestates/Memory-It#21]
## ISSUE

+ Group: `client`
+ Type:  `feature`
+ Detail:LandingPage 안의 Header, SideDescription, GoToMyPost, Demonstration, ToLogin, ToSignup 컴포넌트를 작성합니다.
## TODO
- [ ] Header 컴포넌트 작성
- [ ] SideDescription 컴포넌트 작성
- [ ] GoToMyPost 컴포넌트 작성
- [ ] Demonstration 컴포넌트 작성
- [ ] ToLogin 컴포넌트 작성
- [ ] ToSignup 컴포넌트 작성
## Estimated time

- [ ] 6h
## Labels
Estimated time: `E: 6h`
Group : `client`
Sprint: `Sprint__2__`
Urgency: `High`
