### ISSUE TITLE
[Task] (사용자정보) 로그아웃

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/Memory-It#22]
## ISSUE
+ Group: `server`
+ Type: `feature`
+ Detail: 로그아웃 요청 처리

## TODO
- [x] 로그인된 상태로 로그아웃 요청을 보낸건지 확인
- [x] 로그인이 안된상태라면 오류코드 응답
- [x] 로그인된 상태라면 accessToken, refreshToken제거

## Estimated time

- [x] 3h

## Labels
Estimated time: `E: 3h`
Group : `server`
Urgency: `Middle`
