### ISSUE TITLE
[Task] (사용자정보) 회원탈퇴

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/Memory-It#26]
## ISSUE
+ Group: `server`
+ Type: `feature`
+ Detail: 회원탈퇴 처리

## TODO
- [x] 토큰이 유효한지에 따른 처리
- [x] 유효한 accessToken을 가지고 있다면 TypeORM을 이용해서 해당유저의 정보를 제거
- [ ] 3일이내 복구가능(optional)
- [x] 유효하지 않은 토큰이거나 토큰이 없다면 오류코드 응답

## Estimated time

- [x] 3h

## Labels
Estimated time: `E: 3h`
Group : `server`
Urgency: `Middle`
