### ISSUE TITLE
[Task] 최초배포(HTTPS도메인)

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/Memory-It#4]
## ISSUE
+ Group: `server` 
+ Type: `feature`
+ Detail: S3, EC2, RDS, CloudFront, Route53, ELB, HTTPS도메인 연결 후 'hello world'+쿠키 전달 까지 성공

## TODO
- [x] test server 구축 후 ec2로 구동
- [x] test client 구축 후 s3에 업로드
- [x] rds, ec2연동
- [x] cloudFront, ELB, Route53 연동
- [x] HTTPS도메인 테스트

## Estimated time
- [x] 1d

## Labels
Estimated time: `E: 1d`
Group : `server`
Urgency: `High`
