### ISSUE TITLE
[Task] (사용자정보) 회원가입

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/Memory-It#9]
## ISSUE

+ Group:  `server`
+ Type: `feature`
+ Detail: 회원가입 요청에 따른 API구축

## TODO
- [x] 회원가입요청 시 유저가 유효한 정보를 입력했는지 확인 후 그에 따른 처리
- [x] 유저가 입력한 정보가 유효하다면 typeORM을 이용해 DB에 저장 후 토큰과 함께 성공응답
- [x] 유저가 입력한 정보가 유효하지 않다면 오류코드 응답

## Estimated time

- [x] 9h

## Labels
Estimated time: `E: 9h`
Group : `server`
Urgency:  `Middle`
